### PR TITLE
WMM2025 and enhancements

### PR DESCRIPTION
**Pull request by cristianob**
This PR changes few things

- Add Typescript .d.ts typing
- Fix the fractional year calculation
- Add WMM2025 model
- Optimizations in the model creation
- Supports `altitude` as the third index of `point()` array (optional for compatibility)
- Supports `should_throw` as optional second parameter of `model()`, so the user can choose depending on their needs. Defaults to true to ensure compatibility with the previous version
- Enhance README with more examples and the `throw` problem
- Add more tests
- Add more values for the tests

### CODE REVIEW

**Comment by cristianob** [comment]
@brianreavis Here is the PR with the WMM2025 model and some other enhancements

**Comment by matthias-ccri** [comment]
I'm not sure if `should_throw` is the best solution, because consumers can wrap the geomagnetism call in a try-catch just as easily. 

`should_throw` is optional but it defaults to `true`, which is an antipattern IMO. Optional params should default to `false`.

It takes the second parameter slot, and IMO an options object would be better, so it can be expanded in the future.

In that vein, "should throw" according to the readme is more than just that. It also controls the fallback behavior. It could have a better name, like `fallbackToNearestValidModel` (we can workshop that name).

You just don't see many libs with parameters like `should_throw`...

Other solutions to think about:
- allow `date` to be optional --- when omitted, assume the user wants the value for the current date or the nearest value. (i.e. "automatic mode").
- return undefined if out of bounds? (not sure how well this would fit with the existing api)

**Comment by brianreavis** [comment]
Hey @cristianob, this is high-quality work. Thanks!

Thinking through this more and taking in @matthias-ccri’s feedback, I’d suggest:

Change the model method signature to be:
```js
model(date?: Date, allowOutOfBoundsModel?: boolean): GeomagnetismModel;
```

Basically rename and flip the behavior of the second parameter.

Also, can you revert the copyright and author changes? Really appreciate your work here and the quality of this PR, but I don’t think that is customary.

**Comment by cristianob** [comment]
Hey @brianreavis, I will work on that. Sorry for the delay.

Also, I opened my branch for the owner of this repository, I don't know if it is you. Feel free to do any changes

**Comment by cristianob** [comment]
@brianreavis I made those changes as suggested.

I made the second param as `options`, as suggested by @matthias-ccri and added allowOutOfBoundsModel (default false).

**Comment by cristianob** [comment]
I will just send a commit in a few hours, exporting the GeomagnetismOptions interface and fixing some typos in README

**Comment by cristianob** [comment]
@brianreavis I think it is all done

**Comment by brianreavis** [comment]
@cristianob Thanks a bunch! Looks great. This is now out on NPM (0.2.0): https://www.npmjs.com/package/geomagnetism/v/0.2.0

**Pull request merged**
